# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPFinal', '0002_auto_20170603_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hash_tag',
            field=models.TextField(),
        ),
    ]
